### ISSUE TITLE
not handle jquery $.post

### ISSUE THREAD

**Issue by muziling** [acsbendi/Android-Request-Inspector-WebView#6] opened 2023-08-22 16:37 UTC
webview load url   https://hkjx.hhplayer.com/index.php?url=2005AE78846FFAB6ABDC629D04C8F045519E0864A194AC397D3797783B7700D5

return body html contain js like
```
$.post("api.php",{"url":url,"t":t,"key":key,"act":act,"play":play},function(data){
```
webViewRequest.body()  got empty which expected the post json string,  how to fix this?

Had try the fork git https://github.com/daentech/Android-Request-Inspector-WebView,  but no luck, got  empty body too.

**Comment by acsbendi** [comment] 2023-08-28 16:45
@muziling I haven't managed to reproduce this. What device are you using?

To help find the cause, you could also try running [this sample app](https://github.com/andrebcmarinho/webview-post-intercept) with your URL.

**Comment by muziling** [comment] 2023-09-01 06:11
try this :  https://dm84.tv/p/4232-1-7.html  
chrome f12 network debug show when load https://hkjx.hhplayer.com/api.php, it post data to url ,  webview got empty body .

**Comment by acsbendi** [comment] 2023-09-03 14:27
@muziling I've checked the website, and the issue is that https://hkjx.hhplayer.com/api.php is called from an iframe in https://dm84.tv/p/4232-1-7.html. As [mentioned in the repo's README](https://github.com/acsbendi/Android-Request-Inspector-WebView#caveats), it is not possible to execute JavaScript code in iframes in Android WebViews, so this is not something that can be fixed in this library unfortunately. 

As a workaround, you could load the iframe's source URL directly in the WebView (https://hkjx.hhplayer.com/index.php?url=2005AE78846FFAB6ABDC629D04C8F045519E0864A194AC397D3797783B7700D5 rather than https://dm84.tv/p/4232-1-7.html). If you don't know this URL at compile time, you can also retrieve it at run time like this: 
```kotlin
webView.evaluateJavascript("javascript: Array.from(document.getElementsByTagName(\"iframe\")).map((iframe) => iframe.src)") { iframeSourceUrlArray ->
    Log.i("LOG_TAG", "Iframe source URLs: $iframeSourceUrlArray")
}
```

**Closed as completed by acsbendi** 2023-09-03 14:27 UTC
